// Prüfungskatalog für den Prüfungsgenerator: Land → Kanton/Bundesland → Prüfungsart → Fach.
// In jeder Region gibt es dieselben Prüfungsarten. Für Schweizer Kantone mit ausgewerteten offiziellen Daten (examdb.js)
// werden diese verwendet («offizielle Daten»); sonst ein allgemeines Profil, mit dem Brainy eine Prüfung im üblichen
// Format erstellt (keine Faktenkarte, Hinweis «keine offiziellen Infos»). Nur Fakten/Richtwerte – keine Prüfungstexte.
import { CANTONS, EXAMS } from './examdb.js';

// Nur Regionen mit eigenen, belegten Daten sind einzeln wählbar; alle übrigen = «ALL» (einheitliches/übliches Format).
const SOURCED_CH = Object.fromEntries([...new Set(EXAMS.map(e => e.canton))].sort((a, b) => CANTONS[a].localeCompare(CANTONS[b])).map(k => [k, CANTONS[k]]));

export const COUNTRIES = {
  CH: { name: 'Schweiz', flag: '🇨🇭', region: 'Kanton', regions: { ...SOURCED_CH, ALL: 'Anderer Kanton' }, allName: 'deinem Kanton', ctx: 'Schweiz: CHF, Schweizer Orte. Schweizer Rechtschreibung (ss statt ß).', scale: 'ch' },
  DE: {
    name: 'Deutschland', flag: '🇩🇪', region: 'Bundesland', allName: 'Deutschland', ctx: 'Deutschland: Euro, deutsche Orte. Deutsche Rechtschreibung (mit ß).', scale: 'de',
    regions: { ALL: 'Alle Bundesländer' },
    states: { BW: 'Baden-Württemberg', BY: 'Bayern', BE: 'Berlin', BB: 'Brandenburg', HB: 'Bremen', HH: 'Hamburg', HE: 'Hessen', MV: 'Mecklenburg-Vorpommern', NI: 'Niedersachsen', NW: 'Nordrhein-Westfalen', RP: 'Rheinland-Pfalz', SL: 'Saarland', SN: 'Sachsen', ST: 'Sachsen-Anhalt', SH: 'Schleswig-Holstein', TH: 'Thüringen' },
  },
  AT: {
    name: 'Österreich', flag: '🇦🇹', region: 'Bundesland', allName: 'Österreich', ctx: 'Österreich: Euro, österreichische Orte und Begriffe (z. B. Jänner, Matura). Rechtschreibung mit ß.', scale: 'at',
    regions: { ALL: 'Alle Bundesländer' },
    states: { B: 'Burgenland', K: 'Kärnten', NOE: 'Niederösterreich', OOE: 'Oberösterreich', S: 'Salzburg', ST: 'Steiermark', T: 'Tirol', V: 'Vorarlberg', W: 'Wien' },
  },
};

// Allgemeines Fachprofil (Richtwerte) – gleiche Felder wie die offiziellen Profile in examdb.js
const P = (title, minutes, { tasks, total, note = '', aids = 'gemäss Prüfungsordnung', form = 'du', answer = 'lines', sections, archetypes = [], topics = [], material } = {}) =>
  ({ title, minutes, form, answer, aids, rules: [`Du hast ${minutes} Minuten Zeit.`, 'Lies jede Aufgabe genau durch und beachte die Punktzahl.', 'Schreibe Lösungswege und Begründungen vollständig auf.'], structure: { tasks, total, points: '', note }, sections, archetypes, topics, material });

const MATHE = (title, minutes, extra = {}) => P(title, minutes, { answer: 'grid', aids: 'Geodreieck, Zirkel; Taschenrechner und Formelsammlung gemäss Vorgabe', archetypes: ['Rechnen und Termumformungen ohne Hilfsmittel', 'Gleichungen und Gleichungssysteme, auch als Textaufgabe', 'Funktionen: Graph, Steigung, Schnittpunkte, Interpretation', 'Geometrie: Flächen, Volumen, Satz des Pythagoras', 'Prozent, Proportionalität, Sachrechnen mit Tabellen/Diagrammen'], ...extra });
const AUFSATZ = (title, minutes, extra = {}) => P(title, minutes, { tasks: 1, note: 'Ein Thema aus mehreren wählen', sections: ['Themenwahl'], archetypes: ['Erörterung zu einer Streitfrage', 'Erzählung oder Erlebnisbericht', 'Textgebundener Aufsatz zu einem kurzen Text', 'Stellungnahme / Leserbrief'], ...extra });
const SPRACHE = (title, minutes, extra = {}) => P(title, minutes, { material: { kind: 'Sach- oder literarischer Text mit Zeilennummern', words: '500–800' }, sections: ['Textverständnis', 'Sprachbetrachtung'], archetypes: ['Inhaltsfragen und Belegstellen mit Zeilenangabe', 'Wortbedeutung und Synonyme im Kontext', 'Grammatik: Wortarten, Satzglieder, Zeitformen', 'Rechtschreibung und Zeichensetzung korrigieren'], ...extra });
const FREMD = (title, minutes, extra = {}) => P(title, minutes, { sections: ['Leseverstehen', 'Wortschatz & Grammatik', 'Schreiben'], material: { kind: 'Kurzer Lesetext in der Fremdsprache', words: '300–500' }, archetypes: ['Leseverstehen: richtig/falsch, Multiple Choice, Fragen beantworten', 'Lückentext mit Verbformen und Zeiten', 'Wortschatz: passende Wörter einsetzen', 'Kurzer Text schreiben (E-Mail, Meinung)'], ...extra });

// Prüfungsarten je Land. kinds = Schlüssel der offiziellen Kantonsprüfungen in examdb.js, die zu dieser Art gehören.
export const TYPES = {
  CH: [
    { id: 'gymi', em: '🏫', name: 'Gymi-Aufnahmeprüfung', stage: 'Übertritt ans Gymnasium', kinds: ['zap1', 'gym'], subjects: { mathe: MATHE('Mathematik', 90, { tasks: 9, total: 40 }), 'deutsch-sprach': SPRACHE('Deutsch – Sprachprüfung', 45, { tasks: 14, total: 45 }), 'deutsch-aufsatz': AUFSATZ('Deutsch – Aufsatz', 75), franz: FREMD('Französisch', 45, { tasks: 8, total: 40 }) } },
    { id: 'fms', em: '🏢', name: 'FMS-Aufnahmeprüfung', stage: 'FMS · HMS · IMS · WMS', kinds: ['fms'], subjects: { mathe: MATHE('Mathematik', 90, { tasks: 9, total: 45 }), 'deutsch-aufsatz': AUFSATZ('Deutsch – Aufsatz', 90), 'deutsch-sprach': SPRACHE('Deutsch – Sprachprüfung', 45, { tasks: 14, total: 45 }), franz: FREMD('Französisch', 45, { tasks: 8, total: 40 }), englisch: FREMD('Englisch', 45, { tasks: 8, total: 40 }) } },
    { id: 'bms', em: '🎒', name: 'BMS-Aufnahmeprüfung', stage: 'Berufsmaturität (BM 1 / BM 2)', kinds: ['bmsauf'], subjects: { mathe: MATHE('Mathematik', 90, { tasks: 10, total: 50 }), deutsch: SPRACHE('Deutsch', 90, { tasks: 12, total: 50, sections: ['Textverständnis', 'Sprachbetrachtung', 'Kurzer Schreibauftrag'] }), franz: FREMD('Französisch', 60, { tasks: 8, total: 50 }), englisch: FREMD('Englisch', 60, { tasks: 8, total: 50 }) } },
    { id: 'kv', em: '💼', name: 'KV-Abschlussprüfung (QV)', stage: 'Kaufleute EFZ (Reform 2023)', kinds: [], note: 'Schriftliche Abschlussprüfung schweizweit gleich organisiert: Handlungskompetenzbereiche b, c und e, 255 Minuten inkl. Pause.', links: [{ label: 'Prüfungsorganisation QV (KFMV)', url: 'https://www.kfmv.ch' }], subjects: {
      qv: P('Schriftliche Abschlussprüfung (HKB b, c, e)', 255, { tasks: 6, total: 100, form: 'Sie', note: 'Fallbasierte Aufgaben zu einem Lehrbetrieb, mit Pause', sections: ['b: Interagieren in einem vernetzten Arbeitsumfeld', 'c: Koordinieren von unternehmerischen Arbeitsprozessen', 'e: Einsetzen von Technologien der digitalen Arbeitswelt'], archetypes: ['Ausgangslage Lehrbetrieb: Situation analysieren und Handlungsoptionen begründen', 'Kommunikation: E-Mail an Kundschaft, Lieferant oder Team verfassen', 'Arbeitsprozess planen, koordinieren und dokumentieren (Ablauf, Termine, Verantwortlichkeiten)', 'Daten mit digitalen Werkzeugen auswerten (Tabelle, Diagramm, Kennzahlen) und interpretieren', 'Datenschutz, Informationssicherheit und Zusammenarbeit im Team beurteilen'] }),
    } },
    { id: 'abu', em: '🛠️', name: 'ABU-Schlussprüfung (QV)', stage: 'Berufslehre EFZ/EBA', kinds: ['abu'], subjects: { abu: P('Allgemeinbildung (ABU)', 120, { tasks: 8, total: 80, form: 'Sie', sections: ['Gesellschaft', 'Sprache & Kommunikation'], archetypes: ['Fallbeispiel Recht: Arbeitsvertrag, Mietvertrag, Kaufvertrag beurteilen', 'Politik: Abstimmungen, Gewaltenteilung, Föderalismus erklären', 'Wirtschaft: Budget, Steuern, Konsumkredit, Versicherungen', 'Ethik/Identität: Standpunkt begründen', 'Sprache: Brief, Stellungnahme, Grafik interpretieren'] }) } },
    { id: 'bmp', em: '📚', name: 'BM-Abschlussprüfung (BMP)', stage: 'Berufsmaturität', kinds: ['bmp'], subjects: { deutsch: AUFSATZ('Deutsch', 180, { form: 'Sie' }), mathe: MATHE('Mathematik', 180, { tasks: 10, total: 60, form: 'Sie' }), englisch: FREMD('Englisch', 120, { tasks: 6, total: 60, form: 'Sie' }), franz: FREMD('Französisch', 120, { tasks: 6, total: 60, form: 'Sie' }), rw: P('Finanz- & Rechnungswesen', 120, { tasks: 6, total: 60, form: 'Sie', answer: 'grid', archetypes: ['Buchungssätze und Abschluss', 'Kalkulation und Deckungsbeitrag', 'Bilanz- und Erfolgsanalyse mit Kennzahlen', 'Abschreibungen, Rückstellungen, Abgrenzungen'] }), wr: P('Wirtschaft & Recht', 120, { tasks: 6, total: 60, form: 'Sie', archetypes: ['Rechtsfall lösen mit Gesetzesartikel (OR/ZGB)', 'Markt und Preisbildung', 'Konjunktur und Wirtschaftspolitik', 'Unternehmensmodell anwenden'] }) } },
    { id: 'matura', em: '🎓', name: 'Matura (schriftlich)', stage: 'Gymnasium', kinds: ['matura'], subjects: { deutsch: AUFSATZ('Deutsch', 240, { form: 'Sie' }), mathe: MATHE('Mathematik', 240, { tasks: 6, total: 60, form: 'Sie', archetypes: ['Analysis: Kurvendiskussion, Extremwertaufgabe, Integral', 'Vektorgeometrie: Geraden, Ebenen, Abstände', 'Stochastik: Binomialverteilung, bedingte Wahrscheinlichkeit', 'Exponentialfunktionen und Wachstum'] }), franz: FREMD('Französisch', 180, { tasks: 5, total: 60, form: 'Sie', archetypes: ['Compréhension écrite d’un texte littéraire', 'Analyse et interprétation', 'Rédaction argumentée (300–400 mots)'] }), englisch: FREMD('Englisch', 180, { tasks: 5, total: 60, form: 'Sie', archetypes: ['Reading comprehension of a literary/non-fiction text', 'Text analysis and interpretation', 'Argumentative essay (300–400 words)'] }), bio: P('Biologie', 180, { tasks: 6, total: 60, form: 'Sie', archetypes: ['Genetik: Erbgänge, Stammbaum', 'Zellbiologie und Stoffwechsel', 'Ökologie und Evolution', 'Experiment auswerten'] }), chemie: P('Chemie', 180, { tasks: 6, total: 60, form: 'Sie', answer: 'grid', archetypes: ['Stöchiometrie', 'Säure-Base und pH', 'Redox', 'Organische Chemie'] }), physik: P('Physik', 180, { tasks: 6, total: 60, form: 'Sie', answer: 'grid', archetypes: ['Mechanik', 'Elektrizität', 'Energie', 'Wellen und Optik'] }) } },
  ],
  DE: [
    { id: 'abitur', em: '🎓', name: 'Abitur (schriftlich)', stage: 'Gymnasiale Oberstufe', note: 'Die Länder nutzen für Deutsch, Mathematik, Englisch und Französisch Aufgaben aus dem gemeinsamen Abitur-Aufgabenpool (IQB). Dauer je nach Land und Kurs (grundlegend/erhöht).', links: [{ label: 'Abitur-Aufgabenpool (IQB)', url: 'https://www.iqb.hu-berlin.de/abitur/' }], subjects: { deutsch: P('Deutsch', 315, { tasks: 1, note: '4 Aufgaben zur Wahl, 1 bearbeiten · erhöhtes Niveau 315 min inkl. Auswahlzeit (grundlegend 255 min)', form: 'Sie', archetypes: ['Interpretation eines literarischen Textes (Epik, Lyrik, Drama)', 'Analyse eines pragmatischen Textes mit Erörterung', 'Materialgestütztes Schreiben (z. B. Kommentar, Essay)', 'Vergleichende Analyse zweier Texte'] }), mathe: MATHE('Mathematik', 300, { tasks: 5, total: 100, form: 'Sie', note: 'Aufgaben aus dem gemeinsamen Pool, vor allem im hilfsmittelfreien Teil A oft ergänzt durch landeseigene Teilaufgaben (IQB-Auswertung 2017–2025)', sections: ['Teil A ohne Hilfsmittel', 'Teil B mit Hilfsmitteln'], archetypes: ['Analysis: Funktionsuntersuchung, Integral, Modellierung', 'Analytische Geometrie: Geraden, Ebenen, Abstände', 'Stochastik: Binomialverteilung, Hypothesentest', 'Pflichtteil ohne Hilfsmittel: kurze Aufgaben'] }), englisch: FREMD('Englisch', 270, { tasks: 3, total: 60, form: 'Sie', sections: ['Reading & Analysis', 'Writing', 'Mediation'], archetypes: ['Comprehension of a non-fiction or literary text', 'Analysis of language and style', 'Comment / creative writing', 'Mediation: German text into English summary'] }), bio: P('Biologie', 270, { tasks: 3, total: 100, form: 'Sie' }), geschichte: P('Geschichte', 270, { tasks: 3, total: 100, form: 'Sie', archetypes: ['Quellenanalyse', 'Darstellung historischer Zusammenhänge', 'Urteil und Erörterung'] }) } },
    { id: 'msa', em: '📘', name: 'Mittlerer Schulabschluss', stage: 'Klasse 10 (Realschulabschluss)', subjects: { deutsch: P('Deutsch', 150, { tasks: 2, total: 60, sections: ['Leseverstehen', 'Schreiben'], archetypes: ['Leseverstehen mit Aufgaben zu Text und Grafik', 'Erörterung oder Stellungnahme', 'Textanalyse eines kurzen literarischen Textes'] }), mathe: MATHE('Mathematik', 135, { tasks: 8, total: 60, sections: ['Basisteil ohne Taschenrechner', 'Wahlteil mit Taschenrechner'] }), englisch: FREMD('Englisch', 120, { tasks: 6, total: 60, sections: ['Listening', 'Reading', 'Writing'] }) } },
    { id: 'esa', em: '📗', name: 'Erster Schulabschluss', stage: 'Klasse 9 (Hauptschulabschluss)', subjects: { deutsch: P('Deutsch', 120, { tasks: 2, total: 50, archetypes: ['Leseverstehen', 'Brief oder Bericht schreiben', 'Rechtschreibung und Grammatik'] }), mathe: MATHE('Mathematik', 100, { tasks: 8, total: 50 }), englisch: FREMD('Englisch', 90, { tasks: 6, total: 50 }) } },
    { id: 'ihk', em: '💼', name: 'IHK-Abschlussprüfung (kaufmännisch)', stage: 'Duale Ausbildung', subjects: { wiso: P('Wirtschafts- und Sozialkunde', 60, { tasks: 30, total: 100, form: 'Sie', answer: 'none', note: 'Überwiegend gebundene Aufgaben (Multiple Choice, Zuordnung)', archetypes: ['Ausbildungsrecht (BBiG, Jugendarbeitsschutz)', 'Arbeitsrecht und Sozialversicherung', 'Unternehmensformen und Rechtsgeschäfte', 'Wirtschaftsordnung und Markt'] }), gp: P('Geschäftsprozesse', 150, { tasks: 5, total: 100, form: 'Sie', archetypes: ['Beschaffung: Angebotsvergleich, Bezugskalkulation', 'Absatz: Kundenauftrag, Verkaufskalkulation', 'Personal: Lohnabrechnung', 'Rechnungswesen: Buchungen, KLR'] }) } },
  ],
  AT: [
    { id: 'ahs', em: '🎓', name: 'Matura AHS (Zentralmatura)', stage: 'AHS-Oberstufe', note: 'Standardisierte Reifeprüfung – österreichweit gleiche Aufgaben am gleichen Tag.', links: [{ label: 'Standardisierte Reifeprüfung (BMBWF)', url: 'https://matura.gv.at/srdp/ablauf' }], subjects: { deutsch: P('Deutsch', 300, { tasks: 2, form: 'Sie', note: 'Drei Themenpakete mit je zwei Aufgaben – ein Paket wählen, zwei Texte schreiben', archetypes: ['Erörterung', 'Kommentar oder Leserbrief', 'Meinungsrede oder Empfehlung', 'Textinterpretation oder Textanalyse', 'Zusammenfassung'] }), mathe: MATHE('Mathematik', 270, { form: 'Sie', sections: ['Teil 1: Grundkompetenzen', 'Teil 2: vertiefte Aufgaben'], note: 'Teil 1 viele kurze Aufgaben, Teil 2 wenige längere Aufgaben', archetypes: ['Grundkompetenzen: Algebra, Funktionen, Analysis, Wahrscheinlichkeit (kurze Aufgaben)', 'Kontextaufgabe mit Funktionen und Modellierung', 'Analysis: Ableitung und Integral im Sachkontext', 'Wahrscheinlichkeit und Statistik'] }), englisch: FREMD('Englisch', 270, { form: 'Sie', sections: ['Listening', 'Reading', 'Language in Use', 'Writing'] }) } },
    { id: 'bhs', em: '🏢', name: 'Reife- und Diplomprüfung BHS', stage: 'HAK · HTL · HLW · BAfEP', note: 'Standardisierte Klausuren in Deutsch, Angewandter Mathematik und Fremdsprachen.', links: [{ label: 'Standardisierte Reife- und Diplomprüfung (BMBWF)', url: 'https://matura.gv.at/srdp/ablauf' }], subjects: { deutsch: P('Deutsch', 300, { tasks: 2, form: 'Sie', note: 'Themenpaket wählen, zwei Texte schreiben' }), mathe: MATHE('Angewandte Mathematik', 270, { form: 'Sie', sections: ['Teil A: Grundkompetenzen', 'Teil B: berufsfeldspezifisch'] }), englisch: FREMD('Englisch', 300, { form: 'Sie', sections: ['Listening', 'Reading', 'Language in Use', 'Writing'] }) } },
    { id: 'brp', em: '📚', name: 'Berufsreifeprüfung', stage: 'Lehre mit Matura / Erwachsene', subjects: { deutsch: P('Deutsch', 300, { tasks: 2, form: 'Sie' }), mathe: MATHE('Mathematik', 270, { form: 'Sie' }), englisch: FREMD('Englisch', 270, { form: 'Sie' }) } },
    { id: 'lap', em: '🛠️', name: 'Lehrabschlussprüfung (Theorie)', stage: 'Lehre', subjects: { fachkunde: P('Fachkunde & Fachrechnen', 120, { tasks: 10, total: 100, form: 'Sie', archetypes: ['Fachbegriffe erklären', 'Berechnungen aus dem Berufsalltag', 'Arbeitsabläufe beschreiben', 'Sicherheit und Normen'] }), wiso: P('Wirtschafts- und Sozialkunde', 60, { tasks: 20, total: 50, form: 'Sie', answer: 'none' }) } },
  ],
};

export const typesOf = country => TYPES[country] || TYPES.CH;
const regionName = (c, r) => r === 'ALL' ? COUNTRIES[c]?.allName : COUNTRIES[c]?.regions?.[r] || r;

// Prüfung für Land/Region/Art auflösen. official = offizielle Kantonsdaten vorhanden (Faktenkarte + Quellen).
export function examFor(country, region, typeId) {
  const T = typesOf(country).find(t => t.id === typeId) || typesOf(country)[0];
  const base = { links: T.links || [], id: `${country}-${region}-${T.id}`, country, region, canton: regionName(country, region), regionLabel: COUNTRIES[country].region, type: T.id, name: T.name, stage: T.stage, em: T.em, note: T.note || '', ctx: COUNTRIES[country].ctx, scale: COUNTRIES[country].scale };
  const fits = e => T.kinds?.includes(e.exam) || (e.alsoFor || []).some(k => T.kinds?.includes(k));
  const off = country === 'CH' ? EXAMS.filter(e => e.canton === region && fits(e)) : [];
  if (off.length) {
    const subjects = {};
    off.forEach(e => Object.entries(e.subjects).forEach(([k, v]) => { const key = off.length > 1 ? `${e.id}:${k}` : k; subjects[key] = { ...v, title: off.length > 1 ? `${v.title} · ${e.name.replace(/\s*\(.*\)$/, '').replace(/^.*?(Lang|Kurz)/, '$1')}` : v.title, _src: e.id }; }));
    const e0 = off[0];
    return { ...base, official: true, owner: e0.owner, archive: e0.archive, requirements: e0.requirements, grading: e0.grading, pass: e0.pass, lang: e0.lang, sources: off.map(e => e.name), subjects };
  }
  return { ...base, official: false, subjects: T.subjects };
}
// Für ai.js / gespeicherte Prüfungen: id = "CH-ZH-gymi"
export function examByKey(id) {
  const [c, r, t] = String(id).split('-');
  return COUNTRIES[c] && t ? examFor(c, r, t) : null;
}
// Hat diese Region für diese Art offizielle Daten?
export const hasOfficial = (country, region, typeId) => { const k = typesOf('CH').find(t => t.id === typeId)?.kinds || []; return country === 'CH' && EXAMS.some(e => e.canton === region && (k.includes(e.exam) || (e.alsoFor || []).some(x => k.includes(x)))); };
